/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutVideosImport } from './routes/_layout/videos'
import { Route as LayoutShopImport } from './routes/_layout/shop'
import { Route as LayoutDietsImport } from './routes/_layout/diets'
import { Route as LayoutDietImport } from './routes/_layout/diet'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutDailycheckImport } from './routes/_layout/dailycheck'
import { Route as LayoutChallengesImport } from './routes/_layout/challenges'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutPlanIdImport } from './routes/_layout/plan/$id'
import { Route as LayoutDietNewImport } from './routes/_layout/diet.new'
import { Route as LayoutChallengeNewImport } from './routes/_layout/challenge.new'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVideosRoute = LayoutVideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShopRoute = LayoutShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDietsRoute = LayoutDietsImport.update({
  id: '/diets',
  path: '/diets',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDietRoute = LayoutDietImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDailycheckRoute = LayoutDailycheckImport.update({
  id: '/dailycheck',
  path: '/dailycheck',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChallengesRoute = LayoutChallengesImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPlanIdRoute = LayoutPlanIdImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDietNewRoute = LayoutDietNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutDietRoute,
} as any)

const LayoutChallengeNewRoute = LayoutChallengeNewImport.update({
  id: '/challenge/new',
  path: '/challenge/new',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/challenges': {
      id: '/_layout/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof LayoutChallengesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dailycheck': {
      id: '/_layout/dailycheck'
      path: '/dailycheck'
      fullPath: '/dailycheck'
      preLoaderRoute: typeof LayoutDailycheckImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diet': {
      id: '/_layout/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof LayoutDietImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diets': {
      id: '/_layout/diets'
      path: '/diets'
      fullPath: '/diets'
      preLoaderRoute: typeof LayoutDietsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shop': {
      id: '/_layout/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof LayoutShopImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/videos': {
      id: '/_layout/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof LayoutVideosImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/challenge/new': {
      id: '/_layout/challenge/new'
      path: '/challenge/new'
      fullPath: '/challenge/new'
      preLoaderRoute: typeof LayoutChallengeNewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diet/new': {
      id: '/_layout/diet/new'
      path: '/new'
      fullPath: '/diet/new'
      preLoaderRoute: typeof LayoutDietNewImport
      parentRoute: typeof LayoutDietImport
    }
    '/_layout/plan/$id': {
      id: '/_layout/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof LayoutPlanIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutDietRouteChildren {
  LayoutDietNewRoute: typeof LayoutDietNewRoute
}

const LayoutDietRouteChildren: LayoutDietRouteChildren = {
  LayoutDietNewRoute: LayoutDietNewRoute,
}

const LayoutDietRouteWithChildren = LayoutDietRoute._addFileChildren(
  LayoutDietRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutChallengesRoute: typeof LayoutChallengesRoute
  LayoutDailycheckRoute: typeof LayoutDailycheckRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutDietRoute: typeof LayoutDietRouteWithChildren
  LayoutDietsRoute: typeof LayoutDietsRoute
  LayoutShopRoute: typeof LayoutShopRoute
  LayoutVideosRoute: typeof LayoutVideosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutChallengeNewRoute: typeof LayoutChallengeNewRoute
  LayoutPlanIdRoute: typeof LayoutPlanIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutChallengesRoute: LayoutChallengesRoute,
  LayoutDailycheckRoute: LayoutDailycheckRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDietRoute: LayoutDietRouteWithChildren,
  LayoutDietsRoute: LayoutDietsRoute,
  LayoutShopRoute: LayoutShopRoute,
  LayoutVideosRoute: LayoutVideosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutChallengeNewRoute: LayoutChallengeNewRoute,
  LayoutPlanIdRoute: LayoutPlanIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/challenges': typeof LayoutChallengesRoute
  '/dailycheck': typeof LayoutDailycheckRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/diet': typeof LayoutDietRouteWithChildren
  '/diets': typeof LayoutDietsRoute
  '/shop': typeof LayoutShopRoute
  '/videos': typeof LayoutVideosRoute
  '/': typeof LayoutIndexRoute
  '/challenge/new': typeof LayoutChallengeNewRoute
  '/diet/new': typeof LayoutDietNewRoute
  '/plan/$id': typeof LayoutPlanIdRoute
}

export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/challenges': typeof LayoutChallengesRoute
  '/dailycheck': typeof LayoutDailycheckRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/diet': typeof LayoutDietRouteWithChildren
  '/diets': typeof LayoutDietsRoute
  '/shop': typeof LayoutShopRoute
  '/videos': typeof LayoutVideosRoute
  '/': typeof LayoutIndexRoute
  '/challenge/new': typeof LayoutChallengeNewRoute
  '/diet/new': typeof LayoutDietNewRoute
  '/plan/$id': typeof LayoutPlanIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/challenges': typeof LayoutChallengesRoute
  '/_layout/dailycheck': typeof LayoutDailycheckRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/diet': typeof LayoutDietRouteWithChildren
  '/_layout/diets': typeof LayoutDietsRoute
  '/_layout/shop': typeof LayoutShopRoute
  '/_layout/videos': typeof LayoutVideosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/challenge/new': typeof LayoutChallengeNewRoute
  '/_layout/diet/new': typeof LayoutDietNewRoute
  '/_layout/plan/$id': typeof LayoutPlanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/challenges'
    | '/dailycheck'
    | '/dashboard'
    | '/diet'
    | '/diets'
    | '/shop'
    | '/videos'
    | '/'
    | '/challenge/new'
    | '/diet/new'
    | '/plan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/challenges'
    | '/dailycheck'
    | '/dashboard'
    | '/diet'
    | '/diets'
    | '/shop'
    | '/videos'
    | '/'
    | '/challenge/new'
    | '/diet/new'
    | '/plan/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/challenges'
    | '/_layout/dailycheck'
    | '/_layout/dashboard'
    | '/_layout/diet'
    | '/_layout/diets'
    | '/_layout/shop'
    | '/_layout/videos'
    | '/_layout/'
    | '/_layout/challenge/new'
    | '/_layout/diet/new'
    | '/_layout/plan/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/challenges",
        "/_layout/dailycheck",
        "/_layout/dashboard",
        "/_layout/diet",
        "/_layout/diets",
        "/_layout/shop",
        "/_layout/videos",
        "/_layout/",
        "/_layout/challenge/new",
        "/_layout/plan/$id"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/challenges": {
      "filePath": "_layout/challenges.tsx",
      "parent": "/_layout"
    },
    "/_layout/dailycheck": {
      "filePath": "_layout/dailycheck.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/diet": {
      "filePath": "_layout/diet.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/diet/new"
      ]
    },
    "/_layout/diets": {
      "filePath": "_layout/diets.tsx",
      "parent": "/_layout"
    },
    "/_layout/shop": {
      "filePath": "_layout/shop.tsx",
      "parent": "/_layout"
    },
    "/_layout/videos": {
      "filePath": "_layout/videos.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/challenge/new": {
      "filePath": "_layout/challenge.new.tsx",
      "parent": "/_layout"
    },
    "/_layout/diet/new": {
      "filePath": "_layout/diet.new.tsx",
      "parent": "/_layout/diet"
    },
    "/_layout/plan/$id": {
      "filePath": "_layout/plan/$id.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
