/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VideosImport } from './routes/videos'
import { Route as ChallengesImport } from './routes/challenges'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PlanIdImport } from './routes/plan/$id'

// Create/Update Routes

const VideosRoute = VideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRoute,
} as any)

const ChallengesRoute = ChallengesImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlanIdRoute = PlanIdImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesImport
      parentRoute: typeof rootRoute
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosImport
      parentRoute: typeof rootRoute
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenges': typeof ChallengesRoute
  '/videos': typeof VideosRoute
  '/plan/$id': typeof PlanIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenges': typeof ChallengesRoute
  '/videos': typeof VideosRoute
  '/plan/$id': typeof PlanIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenges': typeof ChallengesRoute
  '/videos': typeof VideosRoute
  '/plan/$id': typeof PlanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/challenges' | '/videos' | '/plan/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/challenges' | '/videos' | '/plan/$id'
  id: '__root__' | '/' | '/about' | '/challenges' | '/videos' | '/plan/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChallengesRoute: typeof ChallengesRoute
  VideosRoute: typeof VideosRoute
  PlanIdRoute: typeof PlanIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChallengesRoute: ChallengesRoute,
  VideosRoute: VideosRoute,
  PlanIdRoute: PlanIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/challenges",
        "/videos",
        "/plan/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/challenges": {
      "filePath": "challenges.tsx"
    },
    "/videos": {
      "filePath": "videos.tsx"
    },
    "/plan/$id": {
      "filePath": "plan/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
