/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutVideosImport } from './routes/_layout/videos'
import { Route as LayoutShopImport } from './routes/_layout/shop'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutDietsIndexImport } from './routes/_layout/diets/index'
import { Route as LayoutDashboardIndexImport } from './routes/_layout/dashboard/index'
import { Route as LayoutDailycheckIndexImport } from './routes/_layout/dailycheck/index'
import { Route as LayoutChallengesIndexImport } from './routes/_layout/challenges/index'
import { Route as LayoutPlanIdImport } from './routes/_layout/plan/$id'
import { Route as LayoutDietsNewImport } from './routes/_layout/diets/new'
import { Route as LayoutChallengesNewImport } from './routes/_layout/challenges/new'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVideosRoute = LayoutVideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShopRoute = LayoutShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDietsIndexRoute = LayoutDietsIndexImport.update({
  id: '/diets/',
  path: '/diets/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDailycheckIndexRoute = LayoutDailycheckIndexImport.update({
  id: '/dailycheck/',
  path: '/dailycheck/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChallengesIndexRoute = LayoutChallengesIndexImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPlanIdRoute = LayoutPlanIdImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDietsNewRoute = LayoutDietsNewImport.update({
  id: '/diets/new',
  path: '/diets/new',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChallengesNewRoute = LayoutChallengesNewImport.update({
  id: '/challenges/new',
  path: '/challenges/new',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shop': {
      id: '/_layout/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof LayoutShopImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/videos': {
      id: '/_layout/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof LayoutVideosImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/challenges/new': {
      id: '/_layout/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof LayoutChallengesNewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diets/new': {
      id: '/_layout/diets/new'
      path: '/diets/new'
      fullPath: '/diets/new'
      preLoaderRoute: typeof LayoutDietsNewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/plan/$id': {
      id: '/_layout/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof LayoutPlanIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/challenges/': {
      id: '/_layout/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof LayoutChallengesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dailycheck/': {
      id: '/_layout/dailycheck/'
      path: '/dailycheck'
      fullPath: '/dailycheck'
      preLoaderRoute: typeof LayoutDailycheckIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diets/': {
      id: '/_layout/diets/'
      path: '/diets'
      fullPath: '/diets'
      preLoaderRoute: typeof LayoutDietsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutShopRoute: typeof LayoutShopRoute
  LayoutVideosRoute: typeof LayoutVideosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutChallengesNewRoute: typeof LayoutChallengesNewRoute
  LayoutDietsNewRoute: typeof LayoutDietsNewRoute
  LayoutPlanIdRoute: typeof LayoutPlanIdRoute
  LayoutChallengesIndexRoute: typeof LayoutChallengesIndexRoute
  LayoutDailycheckIndexRoute: typeof LayoutDailycheckIndexRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutDietsIndexRoute: typeof LayoutDietsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutShopRoute: LayoutShopRoute,
  LayoutVideosRoute: LayoutVideosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutChallengesNewRoute: LayoutChallengesNewRoute,
  LayoutDietsNewRoute: LayoutDietsNewRoute,
  LayoutPlanIdRoute: LayoutPlanIdRoute,
  LayoutChallengesIndexRoute: LayoutChallengesIndexRoute,
  LayoutDailycheckIndexRoute: LayoutDailycheckIndexRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutDietsIndexRoute: LayoutDietsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/shop': typeof LayoutShopRoute
  '/videos': typeof LayoutVideosRoute
  '/': typeof LayoutIndexRoute
  '/challenges/new': typeof LayoutChallengesNewRoute
  '/diets/new': typeof LayoutDietsNewRoute
  '/plan/$id': typeof LayoutPlanIdRoute
  '/challenges': typeof LayoutChallengesIndexRoute
  '/dailycheck': typeof LayoutDailycheckIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/diets': typeof LayoutDietsIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/shop': typeof LayoutShopRoute
  '/videos': typeof LayoutVideosRoute
  '/': typeof LayoutIndexRoute
  '/challenges/new': typeof LayoutChallengesNewRoute
  '/diets/new': typeof LayoutDietsNewRoute
  '/plan/$id': typeof LayoutPlanIdRoute
  '/challenges': typeof LayoutChallengesIndexRoute
  '/dailycheck': typeof LayoutDailycheckIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/diets': typeof LayoutDietsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/shop': typeof LayoutShopRoute
  '/_layout/videos': typeof LayoutVideosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/challenges/new': typeof LayoutChallengesNewRoute
  '/_layout/diets/new': typeof LayoutDietsNewRoute
  '/_layout/plan/$id': typeof LayoutPlanIdRoute
  '/_layout/challenges/': typeof LayoutChallengesIndexRoute
  '/_layout/dailycheck/': typeof LayoutDailycheckIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/diets/': typeof LayoutDietsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/shop'
    | '/videos'
    | '/'
    | '/challenges/new'
    | '/diets/new'
    | '/plan/$id'
    | '/challenges'
    | '/dailycheck'
    | '/dashboard'
    | '/diets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/shop'
    | '/videos'
    | '/'
    | '/challenges/new'
    | '/diets/new'
    | '/plan/$id'
    | '/challenges'
    | '/dailycheck'
    | '/dashboard'
    | '/diets'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/shop'
    | '/_layout/videos'
    | '/_layout/'
    | '/_layout/challenges/new'
    | '/_layout/diets/new'
    | '/_layout/plan/$id'
    | '/_layout/challenges/'
    | '/_layout/dailycheck/'
    | '/_layout/dashboard/'
    | '/_layout/diets/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/shop",
        "/_layout/videos",
        "/_layout/",
        "/_layout/challenges/new",
        "/_layout/diets/new",
        "/_layout/plan/$id",
        "/_layout/challenges/",
        "/_layout/dailycheck/",
        "/_layout/dashboard/",
        "/_layout/diets/"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/shop": {
      "filePath": "_layout/shop.tsx",
      "parent": "/_layout"
    },
    "/_layout/videos": {
      "filePath": "_layout/videos.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/challenges/new": {
      "filePath": "_layout/challenges/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/diets/new": {
      "filePath": "_layout/diets/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/plan/$id": {
      "filePath": "_layout/plan/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/challenges/": {
      "filePath": "_layout/challenges/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dailycheck/": {
      "filePath": "_layout/dailycheck/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/diets/": {
      "filePath": "_layout/diets/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
